name: Daily Podcast Generation
on:
  schedule:
    - cron: '0 22 * * *' # 22:00 UTC = 6:00 AM Taiwan
  workflow_dispatch:
jobs:
  generate-podcast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Generate and publish podcast
        env:
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
        run: python scripts/main.py
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add audio/daily_podcast_*.mp3 feed.xml
          git commit -m "Add podcast and RSS for $(date +%Y%m%d)"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

